### ISSUE TITLE
Failed to verify IP if it is not on the first results page

### ISSUE THREAD

**Issue by alex-bukach** [xiaotianxt/bypass-cloudflare-for-github-action#3]
I ma getting "Failed to verify IP ... in access rules after 10 retries" error though the access rule is successfully created. As far as I see, the problem is that the rule is not on the first page of results.

**Comment by xiaotianxt** [comment]
Hi alex, thanks for your contribution, could you please pull a request to my repo?

**Comment by alex-bukach** [comment]
@xiaotianxt done!
